language: 
  - ruby
  - node_js

branches:
  only:
  - enterprise
  - master

cache:
  bundler: true
  directories:
    - node_modules
    - ember-app/node_modules
    - ember-accounts/node_modules
    - ember-app/bower_components
    - ember-accounts/bower_components

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - bundle install --jobs=3 --retry=3 --deployment
  - npm install
  - cd ember-app && npm install && cd ..
  - cd ember-accounts && npm install && cd ..
  - npm install -g ember-cli

script: 
  - bundle exec rake
  - cd ember-app && ember test && cd ..
  - cd ember-accounts && ember test && cd ..
