language: 
  - ruby
  - node_js

branches:
  only:
  - enterprise
  - master

install:
  - npm install -g npm@2
  - npm install
  - cd ember-app && npm install && cd ..
  - npm install -g  ember-cli

script: 
  - cd ember-app && ember build && cd ..
