language: 
  - ruby
  - node_js

branches:
  only:
  - enterprise
  - master

install:
  - bundle install --jobs=3 --retry=3 --deployment
  - npm install -g npm@2
  - npm install
  - cd ember-app && npm install && cd ..
  - npm install -g  ember-cli

script: 
  - bundle exec rake
  - cd ember-app && ember test && cd ..
